services:
  - type: web
    name: despachoapp-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: despachoapp-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: despachoapp-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: despachoapp-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: 86400000
      - key: GOOGLE_CLIENT_ID
        value: 1003522218119-mbm24fjvqbk0oc1g2halq5h0lbkptlk7.apps.googleusercontent.com

databases:
  - name: despachoapp-db
    databaseName: despacho_db
    user: despacho_user
    plan: free
